#! /bin/bash

pandoc "$1" --pdf-engine=xelatex --number-sections \
	-V linkcolor:blue -V geometry:margin=2cm -V geometry:a4paper -V fontsize=12pt \
	-H $HOME/.config/pandoc/markdown_headers.tex \
	--highlight-style $HOME/.config/pandoc/code_highlighting.theme \
	-o "$2"

